/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodeInventaire } from './periodeInventaire';
import { Codification } from './codification';
import { Users } from './users';


export interface Inventaire { 
    id_inventaire?: number;
    etat?: string;
    nom_agent?: string;
    observations?: string;
    date_inventaire?: string;
    codification?: Codification;
    periodeInventaire?: PeriodeInventaire;
    user?: Users;
}

